import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

import Link from "next/link";
import { PreviewAlert } from "@/components/preview-alert";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PreviewAlert />
        <div className="max-w-screen-md px-6 mx-auto">
          <header>
            <div className="container flex items-center justify-between py-6 mx-auto">
              <Link href="/" className="text-2xl font-semibold no-underline">
                Next.js for Drupal
              </Link>
              <Link
                href="https://next-drupal.org/docs"
                target="_blank"
                rel="external"
                className="hover:text-blue-600"
              >
                Read the docs
              </Link>
            </div>
          </header>
          <main className="container py-10 mx-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
