import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Plus_Jakarta_Sans} from "next/font/google";
import "@/styles/globals.css";

//Components
import NavBar from "@/components/NavBar";

import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"],variable: '--font-inter', });
const plus_jakarta_sans = Plus_Jakarta_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-plus_jakarta_sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${plus_jakarta_sans.variable} bg-gray-300 relative`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
